### ISSUE TITLE
Allows to confirm deletion

### ISSUE THREAD

**Issue by IfnotFr** [jonathanfievet/jPost-it#1]
Hi and thanks for this amazing plugin !

As a missclick can happen, do you think it is possible to add a `confirm()` on the deletion ?

It can helps avoiding deleting a useful sticky note :)

**Comment by GaetanNaulin** [comment]
Yes it could be awesome, because we use jPost-it in our management project website, and a missclick can close a useful post-it..

**Comment by jonathanfievet** [comment]
Hi ! I'm glad to see the plugin is useful :D 
Your wish is granted !
